.. _exhale_function_namespaceCatch_1a3cbceeab9252d1b752f66a2826e92548:

Function Catch::throw_exception
===============================

- Defined in :ref:`file__home_aakash_mlpack_src_mlpack_tests_catch.hpp`


Function Documentation
----------------------


.. doxygenfunction:: Catch::throw_exception(std::exception const&)
