.. _exhale_function_namespaceCatch_1a48d2c35022dd9d56a1b7ee78ad581eea:

Function Catch::throw_runtime_error
===================================

- Defined in :ref:`file__home_aakash_mlpack_src_mlpack_tests_catch.hpp`


Function Documentation
----------------------


.. doxygenfunction:: Catch::throw_runtime_error(std::string const&)
