.. _exhale_function_namespaceCatch_1a707884e681203fef6bf7dbf752532fa5:

Function Catch::throw_logic_error
=================================

- Defined in :ref:`file__home_aakash_mlpack_src_mlpack_tests_catch.hpp`


Function Documentation
----------------------


.. doxygenfunction:: Catch::throw_logic_error(std::string const&)
